project:
  name: quickstart-jaeger
  shorten_stack_name: true
  template: templates/jaeger-entry-new-vpc.template.yaml
  parameters:
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: us-east-1
    QSS3KeyPrefix: quickstart-jaeger/
  s3_bucket: ''

tests:

  # The most basic Jaeger deployment - all defaults
  inmemory-with-defaults:
    parameters:
      EnvironmentName: simple 
    regions:
    - eu-west-1

  # Jaeger with Otel Collector in front
  inmemory-with-otel:
    parameters:
      EnvironmentName: otel 
      OpenTelemetryCollector: 'Yes'
    regions:
    - eu-west-1

  # Jaeger with Otel Collector + Prometheus metrics
  inmemory-with-otel-and-metrics:
    parameters:
      EnvironmentName: otel-with-metrics 
      ExportMetrics: 'CreateNewWorkspace'
      OpenTelemetryCollector: 'Yes'
    regions:
    - eu-west-1

  # Jaeger with SPM configured. See https://www.jaegertracing.io/docs/1.34/spm/ for details
  inmemory-with-spm:
    parameters:
      EnvironmentName: spm 
      ExportMetrics: 'CreateNewWorkspace'
      OpenTelemetryCollector: 'Yes'
      EnableZPages: 'Yes'
      EnableSPM: 'Yes'
    regions:
    - eu-west-1

  # Jaeger deployment with most optional features enabled
  inmemory-with-optional-features:
    parameters:
      EnvironmentName: optional-features
      DomainName: jaeger.com
      PrivateDNS: CreateNew
      CreateVpcEndpoints: 'Yes'
      ExportMetrics: 'CreateNewWorkspace'
      EnableContainerInsights: 'Yes'
      OpenTelemetryCollector: 'Yes'
      MemoryBallastPercentage: 10
      EnableZPages: 'Yes'
      EnablePprof: 'Yes'
      EnableSPM: 'Yes'
    regions:
    - us-east-1

  elasticsearch-with-spm:
    parameters:
      EnvironmentName: es
      StorageBackend: Elasticsearch
      ExportMetrics: 'CreateNewWorkspace'
      OpenTelemetryCollector: 'Yes'
      EnableZPages: 'Yes'
      EnableSPM: 'Yes'
    regions:
    - eu-west-1