project:
  name: quickstart-jaeger
  shorten_stack_name: true
  template: templates/jaeger-entry-new-vpc.template.yaml
  parameters:
    KeyPairName: --overridden--
    RemoteAccessCIDR: 127.0.0.1/32
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    QSS3KeyPrefix: quickstart-jaeger/
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  s3_bucket: ''

tests:

  deploy-in-2-az-with-defaults:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: 2
    regions:
    - eu-west-1
    - us-east-1