project:
  name: quickstart-jaeger
  shorten_stack_name: true
  template: templates/jaeger-entry-new-vpc.template.yaml
  parameters:
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: us-east-1
    QSS3KeyPrefix: quickstart-jaeger/
  s3_bucket: ''

tests:

  inmemory-2-az-with-defaults:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: 2
    regions:
    - eu-west-1

  inmemory-2-az-with-optional-settings:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: 2
      StorageBackend: InMemory
      DomainName: jaeger.com
      PrivateDNS: CreateNew
      ExportMetrics: 'Yes'
      EnableContainerInsights: 'Yes'
    regions:
    - us-east-1

  elasticsearch-2-az-with-defaults:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: 2
      StorageBackend: Elasticseach
    regions:
    - eu-west-1