AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys Jaeger ECS service configured to use in-memory storage (TODO)

Parameters:
  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: ID of your existing VPC (e.g., vpc-0343606e).
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    Type: String  
  PrivateSubnet1ID:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2ID:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet3ID:
    Type: String
    Default: ''
  ClusterArn:
    Type: String
  LoadBalancerDomainName:
    Type: String
  LoadBalancerArn:
    Type: String
  JaegerVersion:
    Type: String

Conditions:
  Using3AvailabilityZones:  !Not [!Equals [!Ref PrivateSubnet3ID, '']]

Resources:

# Target Groups
  TargetGroup14250:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: jaeger-14250
      Port: 14250
      Protocol: TCP
      TargetType: ip
      VpcId: !Ref VPCID

  TargetGroup14268:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: jaeger-14268
      Port: 14268
      Protocol: TCP
      TargetType: ip
      VpcId: !Ref VPCID

  TargetGroup14269:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: jaeger-14269
      Port: 14269
      Protocol: TCP
      TargetType: ip
      VpcId: !Ref VPCID

  TargetGroup16686:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: jaeger-16686
      Port: 16686
      Protocol: TCP
      TargetType: ip
      VpcId: !Ref VPCID

# Listeners
  Listener14250:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: TargetGroup14250
          Type: forward
      LoadBalancerArn: !Ref LoadBalancerArn
      Port: 14250
      Protocol: TCP

  Listener14268:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: TargetGroup14268
          Type: forward
      LoadBalancerArn: !Ref LoadBalancerArn
      Port: 14268
      Protocol: TCP

  Listener14269:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: TargetGroup14269
          Type: forward
      LoadBalancerArn: !Ref LoadBalancerArn
      Port: 14269
      Protocol: TCP
  
  Listener16686:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: TargetGroup16686
          Type: forward
      LoadBalancerArn: !Ref LoadBalancerArn
      Port: 16686
      Protocol: TCP

# Roles
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
        Version: "2012-10-17"

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
        Version: "2012-10-17"
      Policies:
        - PolicyName: jaeger-all-in-one-execution-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
          - Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: !GetAtt LogGroup.Arn

# Task Definition
  LogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: jaeger-all-in-one
          Essential: true
          Image: !Sub jaegertracing/all-in-one:${JaegerVersion}
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Ref: LogGroup
              awslogs-stream-prefix: jaeger-all-in-one
              awslogs-region:
                Ref: AWS::Region
          PortMappings:
            - ContainerPort: 9411
              Protocol: tcp
            - ContainerPort: 14250
              Protocol: tcp
            - ContainerPort: 14268
              Protocol: tcp
            - ContainerPort: 14269
              Protocol: tcp
            - ContainerPort: 16685
              Protocol: tcp
            - ContainerPort: 16686
              Protocol: tcp
          Environment:
            - Name: SPAN_STORAGE_TYPE
              Value: memory
      Cpu: "1024"
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      Family: jaeger-all-in-one-task-definition
      Memory: "2048"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn: !GetAtt TaskRole.Arn

# Service
  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: jaeger-all-in-one
      Cluster: !Ref ClusterArn
      DesiredCount: 1
      HealthCheckGracePeriodSeconds: 30
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: jaeger-all-in-one
          ContainerPort: 16686
          TargetGroupArn:
            Ref: TargetGroup16686
        - ContainerName: jaeger-all-in-one
          ContainerPort: 14250
          TargetGroupArn:
            Ref: TargetGroup14250
        - ContainerName: jaeger-all-in-one
          ContainerPort: 14268
          TargetGroupArn:
            Ref: TargetGroup14268
        - ContainerName: jaeger-all-in-one
          ContainerPort: 14269
          TargetGroupArn:
            Ref: TargetGroup14269
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !GetAtt ServiceSecurityGroup.GroupId
          Subnets:
            - !Ref PrivateSubnet1ID
            - !Ref PrivateSubnet2ID
            - !If [Using3AvailabilityZones, !Ref PrivateSubnet3ID, !Ref 'AWS::NoValue']
      TaskDefinition: !Ref TaskDefinition
    DependsOn:
      - Listener14250
      - Listener14268
      - Listener14269
      - Listener16686

  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: quickstart-jaeger/jaeger/jaeger-all-in-one-service/SecurityGroup
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        - CidrIp: !Ref VPCCIDR
          Description: Allow ECS Service access from within VPC
          FromPort: 0
          IpProtocol: tcp
          ToPort: 65535
      VpcId: !Ref VPCID

Outputs:
  ScrapeTargets:
    Value: !Sub "${LoadBalancerDomainName}:14269"