AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys Jaeger ECS service configured to use in-memory storage (TODO)

Parameters:
# Basic Configuration
  EnvironmentName:
    Type: String
# VPC parameters
  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: ID of your existing VPC (e.g., vpc-0343606e).
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    Type: String  
  PrivateSubnet1ID:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2ID:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet3ID:
    Type: String
    Default: ''
# Jaeger parameters
  ClusterArn:
    Type: String
  LoadBalancerArn:
    Type: String
  LoadBalancerDomainName:
    Type: String
  JaegerVersion:
    Type: String
  ExportMetrics:
    Type: String
    AllowedValues: [ 'Disabled', 'UseExistingWorkspace', 'CreateNewWorkspace' ]
  EnableSPM:
    Type: String
    AllowedValues: [ 'Yes', 'No' ]
  CertificateArn:
    Type: String
  # Metrics
  PrometheusWorkspaceId:
    Type: String

Conditions:
  Using3AvailabilityZones:  !Not [!Equals [!Ref PrivateSubnet3ID, '']]
  ExportMetrics: !Not [!Equals [!Ref ExportMetrics, 'Disabled']]
  EnableSPM: !Equals [!Ref EnableSPM, 'Yes']
  CertificateProvided: !Not [!Equals [!Ref CertificateArn, '']]
  NoCertificateProvided: !Equals [!Ref CertificateArn, '']

Resources:

# Target Groups
  TargetGroup14250:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 14250
      Protocol: TCP
      TargetType: ip
      VpcId: !Ref VPCID
      Tags:
        - Key: Name
          Value: !Sub jaeger-14250-${EnvironmentName}

  TargetGroup14268:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 14268
      Protocol: TCP
      TargetType: ip
      VpcId: !Ref VPCID
      Tags:
        - Key: Name
          Value: !Sub jaeger-14268-${EnvironmentName}

  TargetGroup14269:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Condition: ExportMetrics
    Properties:
      Port: 14269
      Protocol: TCP
      TargetType: ip
      VpcId: !Ref VPCID
      Tags:
        - Key: Name
          Value: !Sub jaeger-14269-${EnvironmentName}

  TargetGroupHttp:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Condition: NoCertificateProvided
    Properties:
      Port: 80
      Protocol: TCP
      TargetType: ip
      VpcId: !Ref VPCID
      Tags:
        - Key: Name
          Value: !Sub jaeger-http-${EnvironmentName}

  TargetGroupHttps:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Condition: CertificateProvided
    Properties:
      Port: 443
      Protocol: TCP
      TargetType: ip
      VpcId: !Ref VPCID
      Tags:
        - Key: Name
          Value: !Sub jaeger-https-${EnvironmentName}

# Listeners
  Listener14250:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: TargetGroup14250
          Type: forward
      LoadBalancerArn: !Ref LoadBalancerArn
      Port: 14250
      Protocol: TCP

  Listener14268:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: TargetGroup14268
          Type: forward
      LoadBalancerArn: !Ref LoadBalancerArn
      Port: 14268
      Protocol: TCP

  Listener14269:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition: ExportMetrics
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: TargetGroup14269
          Type: forward
      LoadBalancerArn: !Ref LoadBalancerArn
      Port: 14269
      Protocol: TCP
  
  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition: NoCertificateProvided
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: TargetGroupHttp
          Type: forward
      LoadBalancerArn: !Ref LoadBalancerArn
      Port: 80
      Protocol: TCP

  HttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition: CertificateProvided
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: TargetGroupHttps
          Type: forward
      LoadBalancerArn: !Ref LoadBalancerArn
      Port: 443
      Protocol: TLS
      SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
      Certificates:
        - CertificateArn: !Ref CertificateArn

# Roles
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      Policies:
        - !If 
          - EnableSPM
          - PolicyName: jaeger-all-in-one-prometheus-access
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - aps:QueryMetrics
                    - aps:GetLabels
                    - aps:GetSeries
                    - aps:GetMetricMetadata
                  Resource: !Sub "arn:${AWS::Partition}:aps:${AWS::Region}:${AWS::AccountId}:workspace/${PrometheusWorkspaceId}"
          - !Ref "AWS::NoValue"

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      Policies:
        - PolicyName: jaeger-all-in-one-execution-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource: !GetAtt LogGroup.Arn

# Task Definition
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 30

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub quickstart-jaeger-all-in-one-${EnvironmentName}
      Cpu: "1024"
      Memory: "2048"
      NetworkMode: awsvpc
      RequiresCompatibilities: [ FARGATE ]
      TaskRoleArn: !GetAtt TaskRole.Arn
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      ContainerDefinitions:
        - Name: jaeger-all-in-one
          Essential: true
          Image: !Sub jaegertracing/all-in-one:${JaegerVersion}
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Ref: LogGroup
              awslogs-stream-prefix: jaeger-all-in-one
              awslogs-region:
                Ref: AWS::Region
          PortMappings:
            - ContainerPort: 9411
              Protocol: tcp
            - ContainerPort: 14250
              Protocol: tcp
            - ContainerPort: 14268
              Protocol: tcp
            - ContainerPort: 14269
              Protocol: tcp
            - ContainerPort: 16685
              Protocol: tcp
            - ContainerPort: 16686
              Protocol: tcp
          Environment:
            - Name: SPAN_STORAGE_TYPE
              Value: memory
            - !If 
              - EnableSPM
              - Name: METRICS_STORAGE_TYPE
                Value: prometheus
              - !Ref "AWS::NoValue" 
            - !If 
              - EnableSPM
              - Name: PROMETHEUS_SERVER_URL
                Value: !Sub "http://localhost:9090/workspaces/${PrometheusWorkspaceId}"
              - !Ref "AWS::NoValue" 
        - !If 
          - EnableSPM
          - Name: sigv4-proxy
            Image: public.ecr.aws/aws-observability/aws-sigv4-proxy:latest # TODO
            Essential: true
            Command:
              - "--port=:9090"
              - "--name=aps"
              - !Sub "--region=${AWS::Region}"
              - !Sub "--host=aps-workspaces.${AWS::Region}.amazonaws.com"
            LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-group: !Ref LogGroup
                awslogs-stream-prefix: jaeger-all-in-one-sigv4-proxy
                awslogs-region: !Ref AWS::Region
          - !Ref "AWS::NoValue" 

# Service
  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: jaeger-all-in-one
      Cluster: !Ref ClusterArn
      DesiredCount: 1
      HealthCheckGracePeriodSeconds: 30
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: jaeger-all-in-one
          ContainerPort: 16686
          TargetGroupArn: !If [CertificateProvided, !Ref TargetGroupHttps, !Ref TargetGroupHttp]
        - ContainerName: jaeger-all-in-one
          ContainerPort: 14250
          TargetGroupArn: !Ref TargetGroup14250
        - ContainerName: jaeger-all-in-one
          ContainerPort: 14268
          TargetGroupArn: !Ref TargetGroup14268
        - !If 
          - ExportMetrics
          - ContainerName: jaeger-all-in-one
            ContainerPort: 14269
            TargetGroupArn: !Ref TargetGroup14269
          - !Ref "AWS::NoValue"
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !GetAtt ServiceSecurityGroup.GroupId
          Subnets:
            - !Ref PrivateSubnet1ID
            - !Ref PrivateSubnet2ID
            - !If [Using3AvailabilityZones, !Ref PrivateSubnet3ID, !Ref 'AWS::NoValue']
      TaskDefinition: !Ref TaskDefinition
      Tags:
        # A necessary trick to force CloudFormation to wait until all listeners are created.
        # We extract listener ID from ARN, as not all characters are allowed in tags. ARN format: 
        # arn:{partition}:elasticloadbalancing:{region}:{account-id}:listener/net/{nlb-name}/{nlb-id}/{listener-id}
        - Key: ListenerIds
          Value: !Join
            - ' '
            - - !Select [4, !Split ['/', !Select [5, !Split [':', !Ref Listener14250]]]] 
              - !Select [4, !Split ['/', !Select [5, !Split [':', !Ref  Listener14268]]]]
              - !Select [4, !Split ['/', !Select [5, !Split [':', !If [CertificateProvided, !Ref HttpsListener, !Ref HttpListener]]]]] 
              - !If [ExportMetrics, !Select [4, !Split ['/', !Select [ 5, !Split [':', !Ref  Listener14269]]]], !Ref 'AWS::NoValue']

  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: quickstart-jaeger/jaeger/jaeger-all-in-one-service/SecurityGroup
      VpcId: !Ref VPCID
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
      SecurityGroupIngress:
        - CidrIp: !Ref VPCCIDR
          Description: Allow ECS Service access (port 16686) from within VPC
          IpProtocol: tcp
          FromPort: 16686
          ToPort: 16686
        - CidrIp: !Ref VPCCIDR
          Description: Allow ECS Service access (port 14250) from within VPC
          IpProtocol: tcp
          FromPort: 14250
          ToPort: 14250
        - CidrIp: !Ref VPCCIDR
          Description: Allow ECS Service access (port 14268) from within VPC
          IpProtocol: tcp
          FromPort: 14268
          ToPort: 14268
        - !If 
          - ExportMetrics
          - CidrIp: !Ref VPCCIDR
            Description: Allow ECS Service access (port 14269) from within VPC
            IpProtocol: tcp
            FromPort: 14269
            ToPort: 14269
          - !Ref "AWS::NoValue"

Outputs:
  ScrapeTargets:
    Value: !Sub "${LoadBalancerDomainName}:14269"