AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys a Jaeger distributed tracing backend into an existing VPC (TODO)
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - E0002
  QuickStartDocumentation:
    EntrypointName: "Launch into an existing VPC"
    Order: Index b
  LintSpellExclude:
    - Docker
    - Jaeger
    - Resource Name
    - Container Insights
    - Route 53
    - Certificate Manager
    - '"No"'
    - '"Yes"'
    - '"Enabled"'
    - namespace
    - cron
    - vpc
    - kubectl
    - dind
    - Gb
    - Multi-AZ
    - External
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Basic configuration
        Parameters:
          - EnvironmentName
      - Label:
          default: VPC network configuration
        Parameters:
          - VPCID
          - VPCCIDR
          - PrivateSubnet1ID
          - PrivateSubnet2ID
          - PrivateSubnet3ID
          - PublicSubnet1ID
          - PublicSubnet2ID
          - PublicSubnet3ID
      - Label:
          default: Jaeger configuration
        Parameters:
          - JaegerVersion
          - StorageBackend
          - InternalLoadBalancer
      - Label:
          default: OpenTelemetry Collector configuration
        Parameters:
          - OpenTelemetryCollector
          - OpenTelemetryCollectorImage
          - OpenTelemetryCollectorVersion
      - Label:
          default: "[Only for Elasticsearch backend] Elasticsearch configuration"
        Parameters:
          - ESEngineVersion
          - ESInstanceCount
          - ESInstanceType
          - ESVolumeSize
          - ESVolumeType
          - ESDependenciesJobSchedule
          - ESDependenciesJobTimeRange
      - Label:
          default: Metrics configuration
        Parameters:
          - EnableContainerInsights
          - ExportMetrics
          - ScrapeIntervalSeconds
          - ScrapeTimeoutSeconds
          - ClusterMetricsCollectionInterval
      - Label:
          default: DNS configuration
        Parameters:
          - DomainName
          - SubdomainName
          - PublicDNS
          - PublicHostedZoneId
          - PrivateDNS
          - PrivateHostedZoneId
          - Certificate
          - CertificateArn
      - Label:
          default: AWS Quick Start configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
          - QSS3BucketRegion
    ParameterLabels:
    # Basic configuration
      EnvironmentName:
        default: Environment name
    # VPC network configuration
      VPCID:
        default: VPC ID
      VPCCIDR:
        default: VPC CIDR
      PublicSubnet1ID:
        default: Public subnet 1 ID
      PublicSubnet2ID:
        default: Public subnet 2 ID
      PublicSubnet3ID:
        default: Public subnet 3 ID
      PrivateSubnet1ID:
        default: Private subnet 1 ID
      PrivateSubnet2ID:
        default: Private subnet 2 ID
      PrivateSubnet3ID:
        default: Private subnet 3 ID
    # Jaeger configuration
      JaegerVersion:
        default: Jaeger version
      StorageBackend:
        default: Jaeger storage backend
      InternalLoadBalancer:
        default: Use internal load balancer
    # OpenTelemetry Collector configuration
      OpenTelemetryCollector:
        default: OpenTelemetry Collector
      OpenTelemetryCollectorImage:
        default: OpenTelemetry Collector image
      OpenTelemetryCollectorVersion:
        default: OpenTelemetry Collector version
    # Elasticsearch configuration
      ESEngineVersion: 
        default: Elasticsearch version
      ESInstanceCount:
        default: Number of data nodes
      ESInstanceType:
        default: Data node instance type
      ESVolumeSize:
        default: Data node volume size
      ESVolumeType:
        default: Data node volume type
      ESDependenciesJobSchedule: 
        default: Dependencies job schedule
      ESDependenciesJobTimeRange: 
        default: Dependencies job time range
    # Metrics configuration
      EnableContainerInsights:
        default: Enable Amazon CloudWatch Container Inrights
      ExportMetrics:
        default: Export Jaeger metrics
      ScrapeIntervalSeconds:
        default: Metrics scrape interval
      ScrapeTimeoutSeconds:
        default: Metrics scrape timeout
      ClusterMetricsCollectionInterval:
        default: Collection interval for ECS cluster metrics 
    # DNS configuration
      DomainName:
        default: Domain name
      SubdomainName:
        default: Subdomain name
      PublicDNS:
        default: Public DNS
      PublicHostedZoneId:
        default: Public Hosted Zone Id
      PrivateDNS:
        default: Private DNS
      PrivateHostedZoneId:
        default: Private Hosted Zone Id
      Certificate:
        default: Certificate
      CertificateArn:
        default: Certificate Arn
    # AWS Quick Start configuration
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3BucketRegion:
        default: Quick Start S3 bucket region
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix

Parameters:

# Basic Configuration
  EnvironmentName:
    Type: String
    Default: ''
    Description: |
      Name of the Jaeger environment (leave empty to use dynamically generated name).
      Environment name is used to generate unique resource names.
      Multiple Jaeger environments with different names can be deployed in the same region.

# VPC parameters
  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: ID of your existing VPC (e.g., vpc-0343606e).
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for the VPC.
    Type: String
  PublicSubnet1ID:
    Type: AWS::EC2::Subnet::Id
    Description: ID of the public subnet in Availability Zone 1 of your existing VPC (e.g., subnet-a0246ccd).
  PublicSubnet2ID:
    Type: AWS::EC2::Subnet::Id
    Description: ID of the public subnet in Availability Zone 2 of your existing VPC (e.g., subnet-b1236eea).
  PublicSubnet3ID:
    Type: String
    Description: ID of the public subnet in Availability Zone 3 of your existing VPC (e.g., subnet-c3456aba).
    Default: ''
  PrivateSubnet1ID:
    Type: AWS::EC2::Subnet::Id
    Description: ID of the private subnet in Availability Zone 1 of your existing VPC (e.g., subnet-fe9a8b32).
  PrivateSubnet2ID:
    Type: AWS::EC2::Subnet::Id
    Description: ID of the private subnet in Availability Zone 2 of your existing VPC (e.g., subnet-be8b01ea).
  PrivateSubnet3ID:
    Type: String
    Description: ID of the private subnet in Availability Zone 3 of your existing VPC (e.g., subnet-abd39039).
    Default: ''
    
# Jaeger parameters
  JaegerVersion:
    Type: String
    Default: '1.32'
    Description: Version of the Jaeger release.
  StorageBackend:
    Type: String
    Default: 'InMemory'
    AllowedValues: [ 'InMemory', 'Elasticseach', 'Cassandra' ]
    Description: Jaeger storage backend.
  InternalLoadBalancer:
    Type: String
    AllowedValues: [ 'Yes', 'No' ]
    Default: 'No'
    Description: Choose "Yes" to deploy Jaeger load balancer in private VPC subnets.

# OpenTelemetry Collector parameters
  OpenTelemetryCollector:
    Type: String
    AllowedValues: [ 'Yes', 'No' ]
    Default: 'No'
    Description: Choose "Yes" to deploy OpenTelemetry Collector in fron of Jaeger.
  OpenTelemetryCollectorImage:
    Type: String
    Default: otel/opentelemetry-collector
    Description: Docker image for the OpenTelemetry Collector
  OpenTelemetryCollectorVersion:
    Type: String
    Default: '0.50.0'
    Description: Version of the OpenTelemetry Collector.

# Elasticsearch parameters
  ESEngineVersion: 
    Type: String
    Default: Elasticsearch_7.10
    Description: | 
      The version of OpenSearch to use. The value must be in the format OpenSearch_X.Y or Elasticsearch_X.Y. 
      For information about supported versions, see https://docs.aws.amazon.com/opensearch-service/latest/developerguide/what-is.html#choosing-version.
  ESInstanceCount:
    Type: Number
    Default: 2
    Description: The number of data nodes (instances) to use in the OpenSearch Service domain.
  ESInstanceType:
    Type: String
    Default: t3.small.search
    Description: |
      The instance type for your data nodes. 
      For valid values, see https://docs.aws.amazon.com/opensearch-service/latest/developerguide/supported-instance-types.html.
  ESVolumeSize:
    Type: Number
    Default: 10
    Description: The size (in GiB) of the EBS volume for each data node.
  ESVolumeType:
    Type: String
    Default: gp2
    Description: The EBS volume type to use with the OpenSearch Service domain, such as standard, gp2, or io1.
  ESDependenciesJobSchedule: 
    Type: String
    Default: '0 1 * * *'
    Description: cron expression that is used to re-build service dependencies (default is daily at 1am).
  ESDependenciesJobTimeRange: 
    Type: String
    Default: '24h'
    Description: |
      How far in the past the job should look to for spans, the maximum and default is `24h`.
      Any value accepted by [date-math](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#date-math) can be used here, but the anchor is always `now`.

# Metrics Scrape parameters
  EnableContainerInsights:
    Type: String
    AllowedValues: [ 'Yes', 'No' ]
    Default: 'No'
    Description: |
      Choose "Yes" to enable integration with CloudWatch Container Insights. 
      Container Insights ensure performance metrics are available in CloudWatch.
  ExportMetrics:
    Type: String
    AllowedValues: [ 'Yes', 'No' ]
    Default: 'No'
    Description: Choose "Yes" to export Jaeger and ECS cluster metrics to Amazon Managed Service for Prometheus.
  ScrapeIntervalSeconds:  
    Type: Number
    Default: 15
    Description: Metrics scrape interval, in seconds
  ScrapeTimeoutSeconds:
    Type: Number
    Default: 10
    Description: Metrics scrape timeout, in seconds
  ClusterMetricsCollectionInterval: 
    Type: Number
    Default: 20
    Description: Collection interval for ECS cluster metrics, in seconds

# DNS parameters
  DomainName:
    Type: String
    Description: The domain name for the Jaeger Query service.
    Default: ''
  SubdomainName:
    Type: String
    Description: The subdomain name for the Jaeger Query service. Jaeger will be available at {subdomain}.{domain} URL.
    Default: jaeger
  PublicDNS:
    Type: String
    AllowedValues: [ 'Disabled', 'UseExisting', 'CreateNew' ]
    Default: 'Disabled'
    Description: |
      Choose "UseExisting" to provide public hosted zone Id where Jaeger DNS record should be created. 
      Choose "CreateNew" to provision a new Route 53 public hosted zone with provided Domain Name and create Jaeger DNS record there.
  PublicHostedZoneId:
    Type: String
    Description: Provide Route 53 public hosted zone Id if you selected "UseExisting" above.
    Default: ''
  PrivateDNS:
    Type: String
    AllowedValues: [ 'Disabled', 'UseExisting', 'CreateNew' ]
    Default: 'Disabled'
    Description: |
      Choose "UseExisting" to provide private hosted zone Id where Jaeger DNS record should be created. 
      Choose "CreateNew" to provision a new Route 53 private hosted zone with provided Domain Name and create Jaeger DNS record there.
  PrivateHostedZoneId:
    Type: String
    Default: ''
    Description: Provide Route 53 public hosted zone Id if you selected "UseExisting" above.
  Certificate:
    Type: String
    AllowedValues: [ 'Disabled', 'UseExisting', 'CreateNew' ]
    Default: 'Disabled'  
    Description: |
      Choose "UseExisting" to provide ACM certificate ARN to use to terminate SSL for Jaeger DNS record. 
      Choose "CreateNew" to provision a new ACM certificate with DNS Domain validation and use it for Jaeger SSL termination.
  CertificateArn:
    Type: String
    Default: ''
    Description: Provide ACM certificate ARN if you selected "UseExisting" above.

# Quickstart location parameters
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description: S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: 'The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.'
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: quickstart-jaeger/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String

Conditions:
  EmptyEnvironmentName: !Equals [!Ref EnvironmentName, '']
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']

Resources:

  Jaeger:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/workload/jaeger-template.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        EnvironmentName: !If [EmptyEnvironmentName, !Ref 'AWS::StackName', !Ref EnvironmentName]
        # VPC parameters
        VPCID: !Ref VPCID
        VPCCIDR: !Ref VPCCIDR
        PublicSubnet1ID: !Ref PublicSubnet1ID
        PublicSubnet2ID: !Ref PublicSubnet2ID
        PublicSubnet3ID: !Ref PublicSubnet3ID
        PrivateSubnet1ID: !Ref PrivateSubnet1ID
        PrivateSubnet2ID: !Ref PrivateSubnet2ID
        PrivateSubnet3ID: !Ref PrivateSubnet3ID
        # Jaeger parameters
        JaegerVersion: !Ref JaegerVersion
        StorageBackend: !Ref StorageBackend
        InternalLoadBalancer: !Ref InternalLoadBalancer
        # OpenTelemetry Collector parameters
        OpenTelemetryCollector: !Ref OpenTelemetryCollector
        OpenTelemetryCollectorImage: !Ref OpenTelemetryCollectorImage
        OpenTelemetryCollectorVersion: !Ref OpenTelemetryCollectorVersion
        # Elasticsearch parameters
        ESEngineVersion: !Ref ESEngineVersion 
        ESInstanceCount: !Ref ESInstanceCount
        ESInstanceType: !Ref ESInstanceType
        ESVolumeSize: !Ref ESVolumeSize
        ESVolumeType: !Ref ESVolumeType
        ESDependenciesJobSchedule: !Ref ESDependenciesJobSchedule 
        ESDependenciesJobTimeRange: !Ref ESDependenciesJobTimeRange
        # Metrics Scrape parameters
        EnableContainerInsights: !Ref EnableContainerInsights
        ExportMetrics: !Ref ExportMetrics
        ScrapeIntervalSeconds: !Ref ScrapeIntervalSeconds
        ScrapeTimeoutSeconds: !Ref ScrapeTimeoutSeconds
        ClusterMetricsCollectionInterval: !Ref ClusterMetricsCollectionInterval
        # DNS parameters
        DomainName: !Ref DomainName
        SubdomainName: !Ref SubdomainName
        PublicDNS: !Ref PublicDNS
        PublicHostedZoneId: !Ref PublicHostedZoneId
        PrivateDNS: !Ref PrivateDNS
        PrivateHostedZoneId: !Ref PrivateHostedZoneId
        Certificate: !Ref Certificate
        CertificateArn: !Ref CertificateArn
        # Quickstart location parameters
        QSS3BucketName: !Ref QSS3BucketName
        QSS3BucketRegion: !Ref QSS3BucketRegion
        QSS3KeyPrefix: !Ref QSS3KeyPrefix

Outputs:
  JaegerURL:
    Value: !GetAtt Jaeger.Outputs.JaegerURL