on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Package templates
        run: |
          ./scripts/package-release.sh quickstart-jaeger-${{ github.ref }}
          zip -r quickstart-jaeger-${{ github.ref }}.zip quickstart-jaeger-${{ github.ref }}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: quickstart-jaeger-${{ github.ref }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
