on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          submodules: 'recursive'
      - name: Set TAG_NAME
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Package templates
        run: |
          ./scripts/package-release.sh quickstart-jaeger-$TAG_NAME
          zip -r quickstart-jaeger-$TAG_NAME.zip quickstart-jaeger-$TAG_NAME
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          artifacts: quickstart-jaeger-$TAG_NAME.zip
          token: ${{ secrets.GITHUB_TOKEN }}
